version: "3"

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: root
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dados-do-banco:/var/lib/mysql
    networks:
      - my-network

volumes:
  dados-do-banco:

networks:
  my-network: